addons:
  apt:
    packages:
      - libpcap-dev
language: rust
rust:
  - nightly
  - beta
  - stable

matrix:
  allow_failures:
    - rust: nightly
cache:
  apt: true
  rust-download: true
  directories:
    - $TRAVIS_BUILD_DIR/target
    - ~/.cargo