# sudo: required
# before_script:
#   - sudo apt-get update -q
#   - sudo apt-get install libpcap-dev
before_script:
  - cargo build
addons:
  apt:
    packages:
      - libpcap-dev
language: rust
rust:
  - nightly
  - beta
  - stable

matrix:
  allow_failures:
    - rust: nightly
cache:
  apt: true
  directories:
    - $TRAVIS_BUILD_DIR/target
    - ~/.cargo