language: rust

addons:
  apt:
    packages:
      - libpcap-dev
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - libudev-dev
rust:
  - nightly
  - beta
  - stable

# whitelist
branches:
  only:
    - master

matrix:
  allow_failures:
    - rust: beta
    - rust: nightly
notifications:
  email:
    on_success: never

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo build &&
      travis-cargo test

after_success:
  - travis-cargo coveralls --no-sudo

sudo: false
