[package]
name = "decode_ceph"
version = "0.1.0"
authors = ["Chris Holcombe <xfactor973@gmail.com>"]

[dependencies]
bitflags = "*"
byteorder = "*"
enum_primitive = "*"
num = "*"
rust-crypto = "*"
time = "*"
